pipeline {
    agent any
    stages {
        stage('Build') 
		{
        
            steps 
			{
                echo 'Hello, Maven'
   
            }
        }
        stage('Deployment') 
		{
            steps 
			{
                echo 'Hello, JDK'
        
            }
        }
    }
}
